package testpaper.entity;
// Generated 2019-7-17 15:23:24 by Hibernate Tools 3.2.2.GA

/**
 * Choice generated by hbm2java
 */
public class Choice implements java.io.Serializable {

	private Integer id;
	private String question;
	private String answer1;
	private String answer2;
	private String answer3;
	private String answer4;
	private Character keyy;
	private Integer picid;
	private Integer comeout;
	private Integer chapter;

	public Choice() {
	}

	public Choice(String question, String answer1, String answer2, String answer3, String answer4) {
		this.question = question;
		this.answer1 = answer1;
		this.answer2 = answer2;
		this.answer3 = answer3;
		this.answer4 = answer4;
	}

	public Choice(String question, String answer1, String answer2, String answer3, String answer4, Character keyy,
			Integer picid, Integer comeout, Integer chapter) {
		this.question = question;
		this.answer1 = answer1;
		this.answer2 = answer2;
		this.answer3 = answer3;
		this.answer4 = answer4;
		this.keyy = keyy;
		this.picid = picid;
		this.comeout = comeout;
		this.chapter = chapter;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getAnswer1() {
		return this.answer1;
	}

	public void setAnswer1(String answer1) {
		this.answer1 = answer1;
	}

	public String getAnswer2() {
		return this.answer2;
	}

	public void setAnswer2(String answer2) {
		this.answer2 = answer2;
	}

	public String getAnswer3() {
		return this.answer3;
	}

	public void setAnswer3(String answer3) {
		this.answer3 = answer3;
	}

	public String getAnswer4() {
		return this.answer4;
	}

	public void setAnswer4(String answer4) {
		this.answer4 = answer4;
	}

	public Character getKeyy() {
		return this.keyy;
	}

	public void setKeyy(Character keyy) {
		this.keyy = keyy;
	}

	public Integer getPicid() {
		return this.picid;
	}

	public void setPicid(Integer picid) {
		this.picid = picid;
	}

	public Integer getComeout() {
		return this.comeout;
	}

	public void setComeout(Integer comeout) {
		this.comeout = comeout;
	}

	public Integer getChapter() {
		return this.chapter;
	}

	public void setChapter(Integer chapter) {
		this.chapter = chapter;
	}

}
