package testpaper.entity;
// Generated 2019-7-17 15:23:24 by Hibernate Tools 3.2.2.GA

/**
 * Picdata generated by hbm2java
 */
public class Picdata implements java.io.Serializable {

	private Integer id;
	private byte[] pic;
	private Integer type;
	private Integer questionid;

	public Picdata() {
	}

	public Picdata(byte[] pic, Integer type, Integer questionid) {
		this.pic = pic;
		this.type = type;
		this.questionid = questionid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public byte[] getPic() {
		return this.pic;
	}

	public void setPic(byte[] pic) {
		this.pic = pic;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getQuestionid() {
		return this.questionid;
	}

	public void setQuestionid(Integer questionid) {
		this.questionid = questionid;
	}

}
