package testpaper.entity;
// Generated 2019-7-15 19:05:21 by Hibernate Tools 3.2.2.GA


/**
 * Picdata generated by hbm2java
 */

public class Picdata implements java.io.Serializable {

	/**
	 * 
	 */

	private int id;
	private byte[] pic;
	private int type;
	private int questionid;

	public Picdata() {
	}

	public Picdata(byte[] pic, int type, int questionid) {
		this.pic = pic;
		this.type = type;
		this.questionid = questionid;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public byte[] getPic() {
		return this.pic;
	}

	public void setPic(byte[] pic) {
		this.pic = pic;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public int getQuestionid() {
		return this.questionid;
	}

	public void setQuestionid(int questionid) {
		this.questionid = questionid;
	}

}
